title = "Example"
description = """
This is an example description.
This is an example description.
"""
[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
"connection_max" = 5000
enabled = true

[servers]
alpha = { ip = '10.0.0.1', dc = "eqdc10" }
beta = { ip = '10.0.0.2', dc = "eqdc10" }

valid-escapes = """\tline \"1\"
    line\u00202
    line 3\U0000002E
"""
